# Generated by Django 6.0 on 2025-12-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
